version: 2.1

orbs:
  codacy: codacy/base@10.2.2
  codacy_plugins_test: codacy/plugins-test@1.1.1

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/sbt:
          name: check_format_and_test
          cmd: |
            sbt "scalafmt::test;
                 test:scalafmt::test;
                 sbt:scalafmt::test;
                 test"
          requires:
            - codacy/checkout_and_version
      - codacy/sbt:
          name: publish_docker_local
          cmd: |
            sbt universal:stage
            docker build -t codacy-aligncheck .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - check_format_and_test
      - codacy_plugins_test/run:
          name: plugins_test
          run_multiple_tests: true
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          filters:
            branches:
              only: master
          requires:
            - plugins_test
      - codacy/tag_version:
          context: CodacyAWS
          requires:
            - codacy/publish_docker
